import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../../styles/BlogPost.module.css'

const Slug = () => {

  const [blog, setblog] = useState({});
  const router = useRouter();

  useEffect(() => {
    if (!router.isReady) return;
    const { slug } = router.query;
    fetch(`http://localhost:3000/api/getblog?slug=${slug}`).then(data => {
      return data.json();
    }).then(data => {
      setblog(data);
    })
  }, [router.isReady])

  return (
    <div className={styles.main}>
      <Head>
        <title>{blog && blog.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.title}>
        <h1>{blog && blog.title}</h1>
      </div>
      <div className={styles.content}>
        {blog && blog.content}
      </div>
    </div>
  )
}

export default Slug