import React from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../../styles/BlogPost.module.css'

const Slug = () => {
  const router = useRouter();
  const { slug } = router.query;
  return (
    <div className={styles.main}>
      <Head>
        <title>{slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.title}>
        <h1>{slug}</h1>
      </div>
      <div className={styles.content}>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Mollitia nesciunt, quo iure non iusto praesentium odio ut illo autem. Repellendus earum numquam exercitationem. Numquam quasi a autem rerum, totam dicta repellendus consectetur facere illum, incidunt, illo aut inventore voluptates atque ab quisquam sapiente enim laborum ducimus laboriosam pariatur? Earum laboriosam vel magni, nostrum officia laudantium excepturi odio quo asperiores sapiente animi rem eveniet sequi quae totam ipsam reprehenderit dolorem voluptates omnis quaerat, velit ipsum! Molestiae ut voluptates quis libero vel, officiis alias voluptatem consequuntur quas iure debitis corporis beatae rem blanditiis tenetur provident obcaecati dolores sequi repudiandae vero labore animi asperiores. Magnam eaque explicabo tempora cumque distinctio autem tempore voluptatibus possimus labore, ipsam quam, voluptates, quis quod voluptatum nihil. Nostrum, asperiores laborum. Commodi et rerum vitae mollitia cum.
      </div>
    </div>
  )
}

export default Slug